//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VehicleConfigurator
{
    using System;
    using System.Collections.Generic;
    
    public partial class VehicleFeatures
    {
        public int VehicleFeaturesId { get; set; }
        public string FeaturesName { get; set; }
        public int FeaturesPrice { get; set; }
        public bool IsStandartPackage { get; set; }
        public int VehicleFeaturesTypeId { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
    
        public virtual VehicleFeaturesType VehicleFeaturesType { get; set; }
    }
}
